fix config

diff --git a/.circleci/continue-config.yml b/.circleci/continue-config.yml
--- a/.circleci/continue-config.yml
+++ b/.circleci/continue-config.yml
@@ -24,22 +24,6 @@ commands:
             echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
             echo 'export USER=${USER:-circleci}' >> $BASH_ENV
             echo '. $HOME/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
-  login_ecr:
-    description: "Logs in to AWS ECR"
-    steps:
-      - run:
-          name: Login to ECR
-          command: |
-            #!/bin/bash -eo pipefail
-            echo "Logging in to ECR..."
-            aws ecr get-login-password --region "${AWS_REGION}" \
-              | docker login \
-                  --username AWS \
-                  --password-stdin "${ECR_REPOSITORY_URI}" 2>&1 || {
-              echo "Error: ECR login failed!"
-              exit 1
-            }
-            echo "ECR login successful."
 
 jobs:
   check:
@@ -80,7 +64,20 @@ jobs:
           docker_layer_caching: true
       - aws-cli/setup:
           role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-uploader-deployer
-      - login_ecr
+      - run:
+          name: Login ECR server
+          command: |
+            #!/bin/bash -eo pipefail
+            echo "Logging in to ECR..."
+            aws ecr get-login-password --region "${AWS_REGION}" \
+              | docker login \
+                  --username AWS \
+                  --password-stdin "${ECR_BACKEND_REPOSITORY_URI}" 2>&1 || {
+              echo "Error: ECR login failed!"
+              exit 1
+            }
+            echo "ECR login successful."
+
       - run:
           name: Upload Image
           command: |
@@ -115,7 +112,19 @@ jobs:
           docker_layer_caching: true
       - aws-cli/setup:
           role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-uploader-deployer
-      - login_ecr
+      - run:
+          name: Login ECR migration
+          command: |
+            #!/bin/bash -eo pipefail
+            echo "Logging in to ECR..."
+            aws ecr get-login-password --region "${AWS_REGION}" \
+              | docker login \
+                  --username AWS \
+                  --password-stdin "${ECR_MIGRATION_REPOSITORY_URI}" 2>&1 || {
+              echo "Error: ECR login failed!"
+              exit 1
+            }
+            echo "ECR login successful."
       - run:
           name: Upload Flyway Image to ECR
           command: |
